namespace HaelpMi.Core.Models;

/// <summary>
/// Fixed at build time by the Install-Creator, shipped as a small JSON file inside the
/// installer payload (see Install-Creator/DeploymentWriter) and copied to
/// <c>{app}\deployment.json</c> next to the executables. Read once at startup - never
/// user-editable, never regenerated by the running app itself.
///
/// <see cref="CustomerGroupId"/> is what lets two independent HälpMi installations
/// coexist on the same physical network without ever seeing each other (Pflichtenheft
/// Teil 2, Abschnitt 6): every network packet carries it, and a receiver silently drops
/// anything with a different value.
/// </summary>
public sealed class DeploymentInfo
{
    public required Guid CustomerGroupId { get; set; }

    /// <summary>
    /// Menschenlesbares Pendant zu <see cref="CustomerGroupId"/> für die Anzeige gegenüber
    /// dem Kunden (z. B. im "Über mich"-Popup) - die UUID selbst soll ein Kunde nie sehen.
    /// Vom Install-Creator pro Installation fortlaufend vergeben, beginnend bei 10001
    /// (siehe Issue #39).
    /// </summary>
    public required int CustomerNumber { get; set; }

    public required Role Role { get; set; }

    /// <summary>
    /// True for installers built with the Install-Creator's "Test-Installer" checkbox
    /// (installer password optional, no customer name required). Never true for a real
    /// deployment - purely a build-time flag carried through so the running app can, if
    /// useful later, show a "Test-Build" marker; nothing in Phase-2 scope currently
    /// branches on it at runtime beyond that.
    /// </summary>
    public bool IsTestInstaller { get; set; }

    /// <summary>
    /// Issue #56: Ed25519-Prüfschlüssel (hex, 64 Zeichen) für die Lizenzsignatur - EIN
    /// eigenes Schlüsselpaar pro <see cref="CustomerGroupId"/>, nicht global (Blast-Radius:
    /// ein kompromittierter Schlüssel betrifft dann nur diese eine Kundengruppe, nicht alle
    /// Kunden). Vom Install-Creator zusammen mit der CustomerGroupId erzeugt, der private
    /// Gegenpart verlässt den Anbieter nie (siehe HaelpMi.InstallCreator.LicenseKeyPairStore).
    /// Ersetzt den früheren fest einkompilierten Platzhalter (siehe #55).
    /// </summary>
    public required string LicensePublicKeyHex { get; set; }
}
